# Generated by Django 3.1.5 on 2021-01-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210131_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defaultthumbnails.jpg', upload_to='posts_thumbnails'),
        ),
    ]
