# Generated by Django 3.1.5 on 2021-01-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defaultthumbnail.jpg', upload_to='posts_thumbnails'),
        ),
    ]
