# Generated by Django 3.1.5 on 2021-02-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=150)),
            ],
        ),
    ]
