# Generated by Django 3.1.5 on 2021-02-01 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='contents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post'),
        ),
    ]
